### PR TITLE
Quote allowed as part of identifiers and test

### PR DESCRIPTION
**Pull request by lpelleau**

### CODE REVIEW

**Comment by Marwes** [comment]
Thanks! Looks good to me, unfortunately travis is having trouble with building Rust today but I will merge this as soon as that issue is fixed https://github.com/travis-ci/travis-ci/issues/6654.

**Comment by lpelleau** [comment]
Saw that too! ok, thank you.

**Comment by Marwes** [comment]
Merged! Thank you

**Comment by brendanzab** [comment]
Thanks! 🎉

**Pull request merged**
