### PR TITLE
Fix primitive! macro for functions with 4 args

### PR DESCRIPTION
**Pull request by MxmUrw**
Added a missing comma in the macro.

(This simple pull request is my first one, i hope it's ok)

### CODE REVIEW

**Comment by brendanzab** [comment]
Thanks!

**Comment by brendanzab** [comment]
I'll merge after the build passes

**Comment by Marwes** [comment]
The earlier nightly regression unfortunately slipped into beta, the fix should be backported but I am not sure how long that takes.

**Comment by MxmUrw** [comment]
Ok

**Comment by Marwes** [comment]
Just explaining why the PR is failing, thanks for the fix! :)

**Pull request merged**
