### PR TITLE
fix: Don't return None from Source::location when byte is at end of file

### PR DESCRIPTION
**Pull request by Marwes**
Since spans are exclusive they may refer to indexes one past the end.

### CODE REVIEW

**Comment by Marwes** [comment]
Only changed the `unwrap`s into `expect` to give some context at least. Is there a better way of handling this instead of panicking? Even if we return `Option`/`Result` I am not sure what we can actually do with that information with the current use of `Infile`.

cc @brendanzab

**Comment by brendanzab** [comment]
The solution here seems kind of ugly... will have to think :/

**Comment by brendanzab** [comment]
Why would we ever get a location of of `src.len()`? Can we fix that instead?

**Comment by brendanzab** [comment]
When exactly does this bug show up?

**Comment by Marwes** [comment]
You can see it by just typing any variable into the repl `foo`. That will give an undefined variable error and panic. We get a position at `src.len()` because the spans are exclusive.

**Comment by Marwes** [comment]
https://gitter.im/Marwes/gluon?at=57d29742c475164703c0e9d3

**Comment by brendanzab** [comment]
Hmm, I wonder how Rust handles this case :/

**Comment by Marwes** [comment]
Best I can tell from https://github.com/rust-lang/rust/blob/master/src/libsyntax/codemap.rs, Rust uses exclusive spans and so allows spans that end at `src.len()`. I think that this method will return a line + row position which may be at `src.len()` as well https://github.com/rust-lang/rust/blob/c87ba3f1222ba20d491e8ed76a04977283280742/src/libsyntax/codemap.rs#L315. Might be wrong though.

**Comment by Marwes** [comment]
@brendanzab Have you been able to come up with a better solution for this?

**Pull request closed without merging**
