### PR TITLE
fix(check): Fix errors uncovered from using (->) partially applied

### PR DESCRIPTION
**Pull request by Marwes**
Also fixes some fallout which was masked by fixing the double listing

### CODE REVIEW

**Comment by Marwes** [comment]
@bjz Though this will fix the immediate error in #37 I think I will take a look at the normalizing issue as well before merging this. If you like I can merge this right away though.

**Comment by bjz** [comment]
Take your time - I'm in no hurry! :)

**Comment by bjz** [comment]
That works :)

**Comment by Marwes** [comment]
Yep, I was just taking a look at the normalizing problem (which isn't actually caused by normalizing but by the unification traversal function changing the order of the arguments).

**Pull request merged**
